# -*- coding: utf-8 -*-
"""Dynamic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_ndq88Adi9nrLhWhl6IwOReIkkaNJsS
"""

!pip install requests-cache

!pip install qiskit

import numpy as np

from numpy import array,arange
# Constants
m = 9.1094e-31     # Mass of electron
hbar = 1.0546e-34  # Planck's constant over 2*pi
e = 1.6022e-19     # Electron charge
L = 5.2918e-11     # Bohr radius
N = 1000
h = L/N
eV = 1.60218e-19

#ne = 1.5*10**23
#ne = 3*10**23
#ne = 4.5*10**23
rou = 1.85
Z = 2
A = 9
ne = (Z/A)*rou*6*10**23
me = m
e0 = np.linspace(2.90,2.96,50)
W = (ne*e**2/e0*me)**1/2
E0 = 2.96*1000*eV
k = 10**10

import matplotlib.pyplot as plt
plt.plot(W)

theta = np.linspace(25,55,50)
c = 299792458 #m/s
E0 = 2.96*eV
k = 4*np.pi*E0/h/c*np.sin(theta/2)
plt.plot(k)
plt.title('Wavenumber')
plt.xlabel('theta')

lambdas = 1/1.6/k
a = 1/k/lambdas 
Wp = W
#k = 7*eV
kB = 1.380649*10**(-23)
T = 12*eV
vth = np.sqrt(kB*T/me)
gamma = h/np.sqrt(2*np.pi*me*kB*T)
W1 = Wp**2 + 3*k**2*vth**2*(1+0.088*ne*gamma**3)+(h**2*k**2/2/me)**2

plt.plot(W1)
plt.title('modified Bohm-Gross')
plt.xlabel('theta')